# .nixpacks/nixpacks.toml

[phases.setup]
# This line tells Railway to install the missing graphics library
nixPkgs = ["...", "ffmpeg", "opencv", "libgl"]

[phases.install]
# This tells Railway how to install your Python packages
cmds = ["pip install -r requirements.txt"]

[start]
# This tells Railway how to start your server
cmd = "gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300"
